### ISSUE TITLE
[Query] Compatibility with PyTorch >=v1.2.0a0

### ISSUE THREAD

**Issue by chaturv3di** [snorkel-team/snorkel#1541] opened 2020-01-31 09:10 UTC
Installing snorkel requires `torch>=1.1.0,<1.2.0`. Are there non-trivial issues that restrict PyTorch version? Is this something that can be helped?

**Comment by vincentschen** [comment] 2020-03-21 23:04
Hi @chaturv3di — At the moment, a few internal implementations rely on those versions of `torch`. Closing this issue as a duplicate of #1558 ~ please see the following comment for more details!
https://github.com/snorkel-team/snorkel/issues/1558#issuecomment-602116595

**Closed by vincentschen** 2020-03-21 23:04 UTC
