### ISSUE TITLE
Bump spaCy dependency to accept v3.0

### ISSUE THREAD

**Issue by rjurney** [snorkel-team/snorkel#1630] opened 2021-02-13 22:51 UTC
## Is your feature request related to a problem? Please describe.

The rest of my environment uses spaCy v3 but Snorkel uses v2. 3.0 is out now.

## Describe the solution you'd like

Remove the <3.0 item from requirements.txt and setup.py

## Describe alternatives you've considered

Maintain more than one conda environment, which is painful.

## Additional context

**Comment by henryre** [comment] 2021-02-14 20:12
Going to close this as a duplicate of #1621

**Closed by henryre** 2021-02-14 20:12 UTC
Labels: duplicate
