### ISSUE TITLE
TypeError: ("'str' object is not callable", 'occurred at index 0')

### ISSUE THREAD

**Issue by Kameronquack** [snorkel-team/snorkel#1421] opened 2019-08-20 22:38 UTC
`from snorkel.labeling import labeling_function
from endpoints import endpoints
import pandas as pd
from snorkel.labeling import PandasLFApplier

data = pd.read_csv('outcome_descriptions.txt', sep="\t", header=None)
print(data)
data['text'] = pd.DataFrame(data)

@labeling_function()
def lf_contains_endpoint(x):
    for t in endpoints:
        if t in x.text():
            return ENDPOINT

lfs = [lf_contains_endpoint]
applier = PandasLFApplier(lfs=lfs)
L_train = applier.apply(df=data)
L_train
`

**Comment by vincentschen** [comment] 2019-08-20 23:44
Hi @Kameronquack — please use the [issue template](https://github.com/snorkel-team/snorkel/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) +  proper code formatting — this makes it much easier to reproduce your error.

With the context I have, my guess it that you're error-ing on `x.text()` — if you're accessing a pandas `DataFrame` directly, this is likely a `str` rather than a function, so including the parens is invalid. 

Does that resolve the issue?

**Comment by Kameronquack** [comment] 2019-08-21 17:46
@vincentschen Yes! This resolved it, thank you so much. I also am having another issue though that comes with it however, when I am trying to check the coverage of it by using 
`coverage_endpoint = (L_train != ABSTAIN).mean(axis=1)
print(f"endpoint coverage: {coverage_endpoint * 100:.1f}%")`
I am receiving the error message 
`File "processendpointlabel.py", line 30, in <module>
    print(f"endpoint coverage: {coverage_endpoint * 100:.1f}%")
TypeError: unsupported format string passed to numpy.ndarray.__format__`

And when I am using 
`LFAnalysis(L=L_train, lfs=lfs).lf_summary()`
I am getting a coverage of 1 with 0 overlaps and 0 conflicts, which makes me believe I am messing up somewhere but not sure where.

**Comment by Kameronquack** [comment] 2019-08-21 18:02
@vincentschen Here is my full code: 
`from snorkel.labeling import labeling_function
from endpoints import endpoints
import pandas as pd
from snorkel.labeling import PandasLFApplier
from snorkel.labeling import LFAnalysis

data = pd.read_csv('outcome_descriptions.txt', sep="\t", header=None)
print(data)
data['text'] = pd.DataFrame(data)
ENDPOINT = 1
ABSTAIN = 0
endpoint_df = pd.DataFrame(endpoints["all"])

print(endpoint_df)
@labeling_function()
def lf_contains_endpoint(x):
    for t in endpoint_df:
        if t in x:
            return ENDPOINT
        else:
            ABSTAIN

# else print("ABSTAIN")


lfs = [lf_contains_endpoint]
applier = PandasLFApplier(lfs=lfs)
L_train = applier.apply(df=data)
L_train
coverage_endpoint = (L_train != ABSTAIN).mean(axis=1)
print(coverage_endpoint)
print(f"endpoint coverage: {coverage_endpoint * 100:.1f}%")
print(LFAnalysis(L=L_train, lfs=lfs).lf_summary())
`

**Comment by vincentschen** [comment] 2019-08-25 17:18
@Kameronquack — looks like it's an issue with non-Snorkel operations; specifically `coverage_endpoint` might be the wrong type to format as a float. 
Make sure that this is `isinstance(coverage_endpoint, float)`?

One note for the future — can you format your code using backtickbacktickbactick for 
```
block code formatting? 
```
This makes it easier to read! (I've gone ahead and formatted your above code in this way.)

**Comment by vincentschen** [comment] 2019-08-25 17:19
Closing this issue, as it looks like the original problem was resolved. Feel free to open another if you encounter any issues with the Snorkel package!

**Closed by vincentschen** 2019-08-25 17:19 UTC
